In [ ]:
import torch
import torch.nn as nn

In [ ]:
cnn_block = nn.Conv1d(in_channels=19, out_channels=64, kernel_size=3, stride=1, padding='valid',bias=True)

num_params = sum(p.numel() for p in cnn_block.parameters() )

print(f"Number of parameters in the CNN block: {num_params}")

Number of parameters in the CNN block: 3712


In [ ]:
dummy_input = torch.randn(19,2048)
print(f"Input shape: {dummy_input.shape}")
output=cnn_block(dummy_input)
print(f"Output shape: {output.shape}")

Input shape: torch.Size([19, 2048])
Output shape: torch.Size([64, 2046])


## Multiple Blocks

In [ ]:

dummy_input = torch.randn(19,2048)
print(f"Input shape: {dummy_input.shape}")


cnn_block1 = nn.Conv1d(in_channels=19, out_channels=64, kernel_size=3, stride=1, padding='valid', bias = True)
cnn_block2 = nn.Conv1d(in_channels=64, out_channels=128, kernel_size=5, stride=1, padding='same', bias = True)
cnn_block3 = nn.Conv1d(in_channels=128, out_channels=256, kernel_size=7, stride=2, padding='valid', bias = True)


output1 = cnn_block1(dummy_input)
print(f"Output shape after block 1: {output1.shape}")

output2 = cnn_block2(output1)
print(f"Output shape after block 2: {output2.shape}")

output3 = cnn_block3(output2)
print(f"Output shape after block 3: {output3.shape}")

Input shape: torch.Size([19, 2048])
Output shape after block 1: torch.Size([64, 2046])
Output shape after block 2: torch.Size([128, 2046])
Output shape after block 3: torch.Size([256, 1020])


In [ ]:
total_params = sum(p.numel() for block in [cnn_block1, cnn_block2, cnn_block3] for p in block.parameters() if p.requires_grad)

print(f"Total number of parameters in the three blocks: {total_params}")

Total number of parameters in the three blocks: 7840


In [ ]:
print(output3)

tensor([[ 0.4540,  0.2282,  0.1932,  ..., -0.0247, -0.0353,  0.2075],
        [ 0.0198,  0.1882, -0.0566,  ...,  0.1568,  0.1471,  0.1638],
        [ 0.0455, -0.1879,  0.3066,  ...,  0.0369,  0.0850,  0.0515],
        ...,
        [ 0.0986,  0.0862,  0.0321,  ...,  0.1973,  0.4183,  0.1162],
        [ 0.0543, -0.2427,  0.2585,  ...,  0.3798,  0.0101,  0.0262],
        [ 0.1427, -0.1718, -0.1146,  ...,  0.2224,  0.2153, -0.0350]],
       grad_fn=<SqueezeBackward1>)


In [ ]:
dummy_inp = torch.randn(64, 4, 4)

MaxPool_layer=nn.AvgPool2d(kernel_size=2)
output=MaxPool_layer(dummy_inp)
print(f"Output shape after MaxPool: {output.shape}")


Output shape after MaxPool: torch.Size([64, 2, 2])


In [ ]:
dummy_inp

tensor([[[ 1.5861,  0.4550,  1.1921, -2.0009],
         [ 0.0782, -1.3011, -0.9906,  0.2244],
         [ 0.7955,  0.1340,  1.7320, -0.9458],
         [ 1.4894,  0.7064, -0.6145,  0.3553]]])

In [ ]:
output

tensor([[[ 0.2046, -0.3937],
         [ 0.7813,  0.1317]]])

## Linear Layer

In [ ]:
layer = nn.Linear(2048, 512, bias = True)

rand_inp = torch.randn(2048)

out = layer(rand_inp)

In [ ]:
out.shape

torch.Size([512])

In [ ]:
num_params = sum(p.numel() for p in layer.parameters() )

print(f"Number of parameters in the CNN block: {num_params}")

Number of parameters in the CNN block: 1049088


In [ ]:
a = 2048
b = 512

print(a*b  + b)

1049088


In [ ]:
random_feature_map = torch.randn(2048, 8, 8)

global_avgpool = nn.AvgPool2d(kernel_size = random_feature_map.shape[-1])

pooled_feature = global_avgpool(random_feature_map)

In [ ]:
pooled_feature.shape

torch.Size([2048, 1, 1])

In [ ]:
pooled_feature.squeeze().shape

torch.Size([2048])